# Generated by Django 2.1.7 on 2019-03-19 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='upload/audios')),
            ],
            options={
                'db_table': 'Audio',
            },
        ),
    ]
