# Generated by Django 2.1.7 on 2019-03-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_recorder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdatedAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_audio', models.FileField(upload_to='upload/updated_audios')),
            ],
            options={
                'db_table': 'Updated_Audio',
            },
        ),
    ]
